# Generated by Django 5.0 on 2023-12-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
